cabs:
  corrupt_visibilities:
    info: Corrupts model visibilities with random phase-only gains and writes to the DATA column.
    flavour: generic
    command: python3 /corrupt_visibilities_app/run.py --ms {{ms}} --seed {{seed}}
    inputs:
      ms:
        dtype: File
        required: true
      seed:
        dtype: int
        default: 42
    volumes:
      - {{ms}}:{{ms}}
